FitJourney/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('register/', include('Register.urls')),
    path('dashboard/', include('Dashboard.urls')),   
    path('goal/', include('Goal.urls')),   
    path('exercise/', include('Exercise.urls')),
    path('planning/', include('planning.urls')),
    path('progress/', include('Progress.urls')),
    path('user/', include('User.urls')),
    path('membership/', include('Membership.urls')),
    path('adminsite/', include('Admin.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Goal/urls.py
# urls.py

from django.urls import path
from . import views

urlpatterns = [
    path('set/', views.set_goal, name='set_goal'),
    path('track/<int:goal_id>/', views.track_progress, name='track_progress'),
    path('history/', views.goal_history, name='goal_history'),
    # Add more URLs as needed
]

User/urls.py
from django.urls import path
from . import views
urlpatterns=[
    path('create',views.create_user, name='create_user'),
    path('update',views.update_user, name='update_user'),
    path('view/profile/',views.user_profile, name='user_profile'),

]

User/models.py
from django.db import models
from Register.models import User
from datetime import date
# Create your models here.


class Member(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile', null=True)
    name = models.CharField(max_length=255, null=True)
    profile_picture = models.ImageField(upload_to='user_profiles/', null=True, blank=True)
    phone = models.CharField(max_length=20, blank=True, null=True)
    DOB= models.DateField(null=True)
    occupation = models.CharField(max_length= 20, null=True)
    address = models.CharField(max_length=30, null=True)
    email = models.CharField(max_length=50, blank=True, null=True)
    
    
    def calculate_age(self):
        if self.DOB:
            today =date.today()
            age = today.year - self.DOB - ((today.month, today.day)<(self.DOB.month, self.DOB.day))
            return age
        return None
        
    

    def __str__(self):
        return f"{self.user.username}'s Profile"

User/forms.py
from django import forms
from .models import Member

class MemberForm(forms.ModelForm):
    class Meta:
        model = Member
        fields = ['name', 'profile_picture', 'phone', 'DOB' ,'occupation', 'address', 'email']
        widgets = {
            'DOB': forms.DateInput(attrs={'type': 'date'}),
        }
     

User/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . models import Member
from django.contrib.auth.decorators import login_required
from .forms import MemberForm
from django.db import IntegrityError
from django.contrib import messages

# Create your views here.


@login_required
def create_user(request):
    user = request.user
    try:
        member = Member.objects.get(user=user)
    except Member.DoesNotExist:
        member = None
        
    if request.method == 'POST':
        member_form = MemberForm(request.POST, request.FILES, instance=member)
        if member_form.is_valid():
            try:
                member = member_form.save(commit=False)
                if not member.user:
                    member.user = user
                member.save()
                messages.success(request, 'Profile Created Successfully!')
                return redirect('user_profile')
            except IntegrityError:
                return render(request, 'User/create_user.html', {
                    'member_form': member_form,
                    'error': 'Profile could not be created due to a database error.'
                })
    else:
        member_form = MemberForm(instance=member)

    return render(request, 'User/create_user.html', {
        'member_form': member_form,
    })
@login_required
def update_user(request):
    user = request.user
    try:
        member = Member.objects.get(user=user)
    except Member.DoesNotExist:
        member = None

    if request.method == 'POST':
        form = MemberForm(request.POST, request.FILES, instance=member)
        if form.is_valid():
            try:
                if member:
                    form.save()  
                else:
                    member = form.save(commit=False)
                    member.user = user
                    member.save()  
                messages.success(request, 'Profile Updated Successfully!')
                return redirect('user_profile') 
            except IntegrityError:
                return render(request, 'User/update_user.html', {'form': form, 'error': 'Visitor profile could not be created due to a database error.'})
    else:
        form = MemberForm(instance=member)

    return render(request, 'User/update_user.html', {'form': form})

@login_required(login_url='login_view')
def user_profile(request):
    user = request.user
    try:
        profile = Member.objects.get(user=user)
    except Member.DoesNotExist:
        return redirect('create_user')

    context = {
        'profile': profile,
    }
    return render(request, 'User/user_profile_page.html', context)

templates/User/create_user.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FitJourney- Create profile</title>
    <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">
    <link rel="stylesheet" href="{% static 'css/create_user.css' %}">
</head>

<body>
    <div class="container">
        <h1>Create your Profile</h1>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %}
          <div class="form-group profile-picture">
            <input type="file" id="id_profile_picture" name="profile_picture" accept="image/*" onchange="previewImage(event)" style="display: none;">
            <label for="id_profile_picture" class="profile-picture-label">
              <img id="profilePreview" src="{%if member_form.instance.profile_picture %}{{member_form.instance.profile_picture.url }}{% else %}{% static 'img/default_profile.png' %}{% endif %}" alt="Profile Picture" class="profile-pic">
              <div class="overlay">
                <img src="{% static 'img/camera.png' %}" alt="Camera Icon" class="camera-icon">
              </div>
            </label>
          </div>
          <h1 class="img-title">Profile picture</h1>
            <div class="form-section-wrapper">
                <div class="section">
                    <!-- Personal Details Section -->
                    <h2>Personal Details</h2>
                    <div class="form-group">
                        {{member_form.non_field_errors }}
                    </div>
                    <div class="form-group">
                        <label for="id_name">Name:</label>
                        {{ member_form.name }}
                    </div>
                    <div class="form-group">
                        <label for="id_biography">Phone:</label>
                        {{member_form.phone }}
                    </div>

                    <div class="form-group">
                        <label for="id_biography">Date of Birth:</label>
                        {{member_form.DOB }}
                    </div>

                    <div class="form-group">
                        <label for="id_biography">Occupation:</label>
                        {{member_form.occupation }}
                    </div>
                    <div class="form-group">
                        <label for="id_contact_phone">Address:</label>
                        {{member_form.address }}
                    </div>
                    <div class="form-group">
                        <label for="id_contact_phone">Email:</label>
                        {{member_form.email }}
                    </div>
                </div>

            <!-- Submit Button -->
            <div class="form-group full-width">
                <button type="submit" class="btn">Create</button>
            </div>

            <!-- Error Message -->
            {% if error %}
            <div class="form-error">
                <p>{{ error }}</p>
            </div>
            {% endif %}
        </form>
    </div>

    <script>
        function previewImage(event) {
            var reader = new FileReader();
            reader.onload = function () {
                var output = document.getElementById('profilePreview');
                output.src = reader.result;
            }
            reader.readAsDataURL(event.target.files[0]);
        }
    </script>
</body>

</html>

templates/User/update_user.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>FitJourney - Update Profile</title>
  <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

  <link rel="shortcut icon" href="{% static 'img/favicon.png' %}" type="image/x-icon">
  <link rel="stylesheet" href="{% static 'css/update_user.css' %}">
</head>

<body>
  <div class="container">
    <h1>Update Your Profile</h1>
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="form-group">
        {{ form.non_field_errors }}
      </div>
      <div class="form-group profile-picture">
        <input type="file" id="id_profile_picture" name="profile_picture" accept="image/*" onchange="previewImage(event)"
          style="display: none;">
        <label for="id_profile_picture" class="profile-picture-label">
          <img id="profilePreview"
            src="{% if form.instance.profile_picture %}{{ form.instance.profile_picture.url }}{% else %}{% static 'img/default_profile.jpg' %}{% endif %}"
            alt="Profile Picture" class="profile-pic">
          <div class="overlay">
            <i class="fas fa-camera camera-icon"></i>
          </div>
        </label>
      </div>

      <div class="form-group">
        <label for="id_name">Name:</label>
        {{ form.name }}
      </div>
      <div class="form-group">
        <label for="id_DOB">Date of Birth:</label>
        {{ form.DOB }}
      </div>
      <div class="form-group">
        <label for="id_phone">Phone:</label>
        {{ form.phone }}
      </div>
      <div class="form-group">
        <label for="id_occupation">Occupation:</label>
        {{ form.occupation }}
      </div>
      <div class="form-group">
        <label for="id_address">Address:</label>
        {{ form.address }}
      </div>
      <div class="form-group">
        <label for="id_address">Address:</label>
        {{ form.email }}
      </div>
      <div class="form-group button-group">
        <button type="submit" class="btn">Save</button>
        <a href="{% url 'user_profile' %}" class="btn cancel-btn">Cancel</a>
      </div>
      {% if error %}
      <div class="form-error">
        <p>{{ error }}</p>
      </div>
      {% endif %}
    </form>
  </div>
</body>
<script>
  function previewImage(event) {
    var reader = new FileReader();
    reader.onload = function () {
      var output = document.getElementById('profilePreview');
      output.src = reader.result;
    }
    reader.readAsDataURL(event.target.files[0]);
  }
</script>

</html>

templates/User/user_profile_page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
<link rel="stylesheet" href="{% static 'css/userprofile.css' %}">
<link rel="stylesheet" href="{% static 'css/style.css' %}">
<div class="container">
    <div class="main-body">
    
        <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            <img src="{% if profile.profile_picture %}{{ profile.profile_picture.url }}{% else %}{% static 'img/default_profile.jpg' %}{% endif %}" alt="Admin" class="rounded-circle" width="150">
                            <div class="mt-3">
                                <h4>{{profile.name}}</h4>
                                <p class="text-secondary mb-1">{{profile.DOB}}</p>
                                <p class="text-muted font-size-sm">{{profile.address}}</p>
                                <button class="btn btn-primary btn-action">Follow</button>
                                <button class="btn btn-outline-primary btn-action">Message</button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card mt-3">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                            <h6 class="mb-0">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram mr-2 icon-inline text-danger"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg><a href="https://www.instagram.com/">Instagram</a>
                            </h6>
                            <span class="text-secondary"></span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                            <h6 class="mb-0">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-facebook mr-2 icon-inline text-primary"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>Facebook
                            </h6>
                            <span class="text-secondary"></span>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-8">
                <div class="card mb-3">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Name</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{profile.name}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">DOB</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{profile.DOB}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Phone</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{profile.phone}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Occupation</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{profile.occupation}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Address</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{profile.address}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-3">
                                <h6 class="mb-0">Email</h6>
                            </div>
                            <div class="col-sm-9 text-secondary">
                                {{profile.email}}
                            </div>
                        </div>
                        <hr>
                        <div class="row">
                            <div class="col-sm-12">
                                <a class="btn btn-info btn-action" target="__blank" href="{% url 'update_user' %}">Edit</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'js/afterlogin.js' %}"></script>
{% endblock %}